version: "2"
services:
        jekyll:
                image: jekyll:xenial
                container_name: jekyll
                ports:
                        - "4000:4000"
                volumes:
                        - "$PWD:/home"
                command: "jekyll serve --host=0.0.0.0 --source=/home --incremental --watch"
